import sqlite3 as sq
import os
def making_database():
    database_name = "projects.db"
    way = os.path.join("..\\mini_project\\databases\\"+database_name)
    db = sq.connect(way)
    cursor = db.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS PROJECTS (NUMBER_OF_PROJECT INT NOT NULL UNIQUE, NAME TEXT, NUM_OF_CUSTOMER INT NOT NULL, \
    PROJECT_MANAGER_NUM TEXT, DURATION_OF_EXECUTION INT, DIFFICULTY_CATEGORY INT NOT NULL, BEGIN_DATE DATE NOT NULL);")
    cursor.execute("CREATE TABLE IF NOT EXISTS ABOUT_COMPANY (PERFORMER_NUMBER INT NOT NULL UNIQUE, F_L_P TEXT, \
    POST TEXT, SKILL_LEVEL TEXT);")
    cursor.execute("CREATE TABLE IF NOT EXISTS PROJECTS_IN_PROGRESS (NUMBER_OF_PROJECT INT NOT NULL UNIQUE, PERFORMER_NUMBER INT NOT NULL, PRICE DOUBLE, FINISH TEXT);")
    cursor.execute("CREATE TABLE IF NOT EXISTS COEFFICIENTS (DIFFICULTY_NUMBER INT NOT NULL UNIQUE, PROJECTS_DIFFICULTY TEXT, \
    ALLOWANCE_COEFFICIENT INT NOT NULL);")
    cursor.execute("CREATE TABLE IF NOT EXISTS CUSTOMERS (CUSTOMERS_NUMBER INT NOT NULL UNIQUE, CUSTOMER_NAME TEXT, NON_PAYING_TERM INT NOT NULL, CHARGE DOUBLE NOT NULL);") #///////
    cursor.execute("CREATE TABLE IF NOT EXISTS PAYROLL (PERFORMER_NUMBER INT NOT NULL UNIQUE, BANK_ACCOUNT_NUMBER TEXT UNIQUE,\
    WAGE DOUBLE);")
    cursor.execute("CREATE TABLE IF NOT EXISTS DEBTORS (NUMBER_OF_DEBTORS INT UNIQUE, CUSTOMER_NUMBER INT,\
    AMOUNT_OF_DEBT DOUBLE, NON_PAYMENT_PER INT)")
    cursor.execute("CREATE TABLE IF NOT EXISTS PAYMENT (POST TEXT, HOURLY_RATE_PAYMENT DOUBLE, ALLOWANCE_RATIO DOUBLE);")
    cursor.execute("CREATE TABLE IF NOT EXISTS REPORT (REPORT_NUMBER INT NOT NULL UNIQUE, PROJECT_NUM INT, CHANGES TEXT, HOURS DOUBLE, PERSON_NUMBER INT)")
    cursor.execute("CREATE TABLE IF NOT EXISTS HISTORY (PERFORMER_NUMBER INT NOT NULL, POSITION TEXT, STATUS TEXT)")
                                                                                                    # СТАТУС (звільнений, прийнятий на роботу)
    db.commit()
    db.close()
making_database()